- name: configure application server
  hosts: app
  become: yes
  tasks:
  - name: default nodejs mdoule disabled
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs mdoule 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest
  
  - name: create expense user
    ansible.builtin.user:
      name: expense
      state: present
    
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip the backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

