- name: configure application server
  hosts: app
  become: yes
  tasks:
  - name: default nodejs mdoule disabled
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs mdoule 
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: latest
  
  - name: create expense user
    ansible.builtin.user:
      name: expense
      state: present
    

