- name: configure db server
  hosts: db
  become: yes
  vars:
    db_host: 172.31.31.225
  vars_prompt:
    name: mysql_pwd
    prompt: enter mysql password
    private: no
  tasks: 
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9
  
  - name: connect to database
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_pwd }}"
      login_host: "{{ db_host }}"
      filter: version
    ignore_errors: yes
    register: db_info

  - name: print data base info
    ansible.builtin.debug:
      msg: "output is : {{ db_info }}"

  - name: set db root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_pwd }} "
    when: db_info.failed is true
  
