- name: configure DB server
  hosts: db 
  vars:
    login_user: root
    login_password: ExpenseApp@1
    login_host: db.sundardev.online
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
      
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install mysql python dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9
  - name: connect DB server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ login_password }}"
      login_host: "{{ login_host }}"
    filter: version
    ignore_errors: yes
    register : mysql_info

  - name: print mysql mysql_info
    ansible.builtin.debug:
      msg: "mysql info is {{ mysql_info }}"

    
    