- name: configure db server
  hosts: db
  become: yes
  vars_prompt:
  - name: DB_PASSWORD
    prompt: enter db password
    private: false
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: installed
      
  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes

  - name: connection database
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ DB_PASSWORD }}"
    ignored_errors: yes
    register: db_info
    

  - name: print db information
    ansible.builtin.debug:
      msg: "db info is : {{db_info}}"