- name: configure the frontend server
  hosts: frontend
  vars:
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name : remove existing default code
    ansible.builtin.command: rm -rf /usr/share/nginx/html